image:
  repository: ghcr.io/home-operations/prowlarr
  pullPolicy: IfNotPresent
  tag: 1.34.1.5021

resources:
  limits:
    cpu: 100m
    memory: 200Mi

prowlarrConfig:
  instanceName: Prowlarr
  additionalEnvs: []

prowlarrNetwork:
  webPort: 30050
  hostNetwork: false

prowlarrRunAs:
  user: 568
  group: 568

prowlarrStorage:
  config:
    type: ixVolume
    ixVolumeConfig:
      datasetName: config
  additionalStorages: []
